# Generated by Django 5.0.6 on 2025-11-03 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать только буквы, цифры и символы @ . - _', regex='^[\\w.@-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
